DROP TABLE IF EXISTS USER_INFO;
DROP TABLE IF EXISTS CAR_INFO;
DROP TABLE IF EXISTS FUEL_TYPE_INFO;
DROP TABLE IF EXISTS MODEL_TYPE_INFO;
DROP TABLE IF EXISTS BODY_TYPE_INFO;
DROP TABLE IF EXISTS ENGINE_INFO;
DROP TABLE IF EXISTS BRAND_INFO;

-- 브랜드 정보
CREATE TABLE BRAND_INFO (
    BRAND_ID INT AUTO_INCREMENT PRIMARY KEY ,
    BRAND_NAME VARCHAR(30) NOT NULL
);

-- 엔진 정보
CREATE TABLE ENGINE_INFO (
    ENGINE_ID INT AUTO_INCREMENT PRIMARY KEY ,
    ENGINE_NAME VARCHAR(30) NOT NULL
);

-- 바디 타입 정보
CREATE TABLE BODY_TYPE_INFO (
    BODY_TYPE_ID INT AUTO_INCREMENT PRIMARY KEY ,
    BODY_TYPE_NAME VARCHAR(30)
);

-- 모델명 정보
CREATE TABLE MODEL_TYPE_INFO (
    MODEL_TYPE_ID INT AUTO_INCREMENT PRIMARY KEY ,
    MODEL_TYPE_NAME VARCHAR(30)
);

-- 연료 정보
CREATE TABLE FUEL_TYPE_INFO (
    FUEL_TYPE_ID INT AUTO_INCREMENT PRIMARY KEY ,
    FUEL_TYPE_NAME VARCHAR(30)
);

-- 자동차 정보
CREATE TABLE CAR_INFO (
    CAR_ID INT AUTO_INCREMENT PRIMARY KEY ,
    CAR_FULL_NAME VARCHAR(100) ,
    CAR_MODEL INT,
    CAR_BRAND INT,
    CAR_BODY_TYPE INT,
    CAR_ENGINE_TYPE INT,
    CAR_FUEL_TYPE INT,
    CAR_PRICE INT,
    CAR_HORSEPOWER INT,
    CAR_FUEL_EFFICIENCY INT,
    CAR_SIZE INT,
    CAR_IMG_URL VARCHAR(100),
    FOREIGN KEY (CAR_MODEL) REFERENCES MODEL_TYPE_INFO(MODEL_TYPE_ID),
    FOREIGN KEY (CAR_BRAND) REFERENCES  BRAND_INFO(BRAND_ID),
    FOREIGN KEY (CAR_BODY_TYPE) REFERENCES BODY_TYPE_INFO(BODY_TYPE_ID),
    FOREIGN KEY (CAR_ENGINE_TYPE) REFERENCES ENGINE_INFO(ENGINE_ID),
    FOREIGN KEY (CAR_FUEL_TYPE) REFERENCES FUEL_TYPE_INFO(FUEL_TYPE_ID)
);

-- 유저 정보
CREATE TABLE USER_INFO (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY ,
    USER_AGE INT NOT NULL ,
    USER_GENDER VARCHAR(10) NOT NULL CHECK (USER_GENDER IN ('남', '여')),
    CAR_ID INT NOT NULL,
    FOREIGN KEY (CAR_ID) REFERENCES CAR_INFO(CAR_ID)
);