DROP TABLE IF EXISTS BODY_TYPE_INFO;
DROP TABLE IF EXISTS COMMENT_INFO;
DROP TABLE IF EXISTS CAR_REVIEW_INFO;
DROP TABLE IF EXISTS CAR_RECOMMENDATION_INFO;
DROP TABLE IF EXISTS USER_INFO;
DROP TABLE IF EXISTS JOB_TYPE_INFO;
DROP TABLE IF EXISTS CAR_INFO;
DROP TABLE IF EXISTS FUEL_TYPE_INFO;
DROP TABLE IF EXISTS BRAND_INFO;


CREATE TABLE `BRAND_INFO` (
  `BRAND_ID` INT NOT NULL,
  `BRAND_NAME` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`BRAND_ID`),
  UNIQUE KEY `BRAND_NAME` (`BRAND_NAME`)
);

CREATE TABLE `FUEL_TYPE_INFO` (
  `FUEL_TYPE_ID` INT NOT NULL,
  `FUEL_TYPE_NAME` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`FUEL_TYPE_ID`),
  UNIQUE KEY `FUEL_TYPE` (`FUEL_TYPE_NAME`)
);

CREATE TABLE `CAR_INFO` (
  `CAR_ID` INT NOT NULL,
  `CAR_FULL_NAME` VARCHAR(255) DEFAULT NULL,
  `CAR_BODY_TYPE` VARCHAR(255) DEFAULT NULL,
  `CATEGORY_ID` INT DEFAULT NULL,
  `CAR_FUEL_TYPE` INT DEFAULT NULL,
  `CAR_PRICE` VARCHAR(255) DEFAULT NULL,
  `CAR_HORSEPOWER` VARCHAR(255) DEFAULT NULL,
  `CAR_FUEL_EFFICIENCY` VARCHAR(255) DEFAULT NULL,
  `CAR_MODEL_YEAR` VARCHAR(255) DEFAULT NULL,
  `CAR_SIZE` VARCHAR(255) DEFAULT NULL,
  `CAR_ENGINE_TYPE` VARCHAR(255) DEFAULT NULL,
  `CAR_IMG_URL` VARCHAR(255) DEFAULT NULL,
  `CAR_BRAND` INT DEFAULT NULL,
  PRIMARY KEY (`CAR_ID`),
  KEY `FK_CAR_BRAND` (`CAR_BRAND`),
  KEY `FK_CAR_FUEL_TYPE` (`CAR_FUEL_TYPE`),
  CONSTRAINT `FK_CAR_BRAND` FOREIGN KEY (`CAR_BRAND`) REFERENCES `BRAND_INFO` (`BRAND_ID`),
  CONSTRAINT `FK_CAR_FUEL_TYPE` FOREIGN KEY (`CAR_FUEL_TYPE`) REFERENCES `FUEL_TYPE_INFO` (`FUEL_TYPE_ID`)
);

CREATE TABLE `JOB_TYPE_INFO` (
  `JOB_ID` INT NOT NULL AUTO_INCREMENT,
  `JOB_NAME` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`JOB_ID`)
);

CREATE TABLE `USER_INFO` (
  `USER_ID` INT NOT NULL AUTO_INCREMENT,
  `USER_AGE` INT NOT NULL,
  `USER_GENDER` VARCHAR(10) NOT NULL,
  `USER_JOB` INT NOT NULL,
  `USER_PURPOSE` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`USER_ID`),
  KEY `USER_JOB` (`USER_JOB`),
  CONSTRAINT `USER_INFO_IBFK_1` FOREIGN KEY (`USER_JOB`) REFERENCES `JOB_TYPE_INFO` (`JOB_ID`),
  CONSTRAINT `USER_INFO_CHK_1` CHECK ((`USER_GENDER` IN ('남', '여')))
);

CREATE TABLE `CAR_RECOMMENDATION_INFO` (
  `RECO_ID` INT NOT NULL AUTO_INCREMENT,
  `USER_ID` INT NOT NULL,
  `CAR_ID` INT NOT NULL,
  PRIMARY KEY (`RECO_ID`),
  KEY `USER_ID` (`USER_ID`),
  KEY `CAR_ID` (`CAR_ID`),
  CONSTRAINT `CAR_RECOMMENDATION_INFO_IBFK_1` FOREIGN KEY (`USER_ID`) REFERENCES `USER_INFO` (`USER_ID`),
  CONSTRAINT `CAR_RECOMMENDATION_INFO_IBFK_2` FOREIGN KEY (`CAR_ID`) REFERENCES `CAR_INFO` (`CAR_ID`)
);

CREATE TABLE `CAR_REVIEW_INFO` (
  `REVIEW_ID` INT NOT NULL AUTO_INCREMENT,
  `CAR_ID` INT DEFAULT NULL,
  `CAR_NAME` VARCHAR(100) NOT NULL,
  `AVG_SCORE` FLOAT NOT NULL,
  `SURVEY_PEOPLE_COUNT` INT DEFAULT NULL,
  `GRAPH_INFO` VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (`REVIEW_ID`),
  KEY `CAR_ID` (`CAR_ID`),
  CONSTRAINT `CAR_REVIEW_INFO_IBFK_1` FOREIGN KEY (`CAR_ID`) REFERENCES `CAR_INFO` (`CAR_ID`)
);

CREATE TABLE `COMMENT_INFO` (
  `COMMENT_ID` INT NOT NULL AUTO_INCREMENT,
  `REVIEW_ID` INT NOT NULL,
  `NICKNAME` VARCHAR(20) NOT NULL,
  `COMMENT_AVG_SCORE` FLOAT DEFAULT NULL,
  `COMMENT_TEXT` VARCHAR(300) DEFAULT NULL,
  `CREATED_AT` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`COMMENT_ID`),
  KEY `FK_COMMENT_INFO` (`REVIEW_ID`),
  CONSTRAINT `FK_COMMENT_INFO` FOREIGN KEY (`REVIEW_ID`) REFERENCES `CAR_REVIEW_INFO` (`REVIEW_ID`)
);

CREATE TABLE `BODY_TYPE_INFO` (
  `BODY_ID` INT NOT NULL,
  `BODY_NAME` VARCHAR(255) NOT NULL,
  `BODY_TYPE_CATEGORY` VARCHAR(255) DEFAULT NULL,
  `CATEGORY_ID` INT DEFAULT NULL,
  UNIQUE KEY `BODY_TYPE` (`BODY_NAME`)
);

LOAD DATA INFILE '/var/lib/mysql-files/brand_info.csv'
INTO TABLE BRAND_INFO
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;


LOAD DATA INFILE '/var/lib/mysql-files/fuel_type_info.csv'
INTO TABLE FUEL_TYPE_INFO
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;

LOAD DATA INFILE '/var/lib/mysql-files/body_type_info.csv'
INTO TABLE BODY_TYPE_INFO
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;

LOAD DATA INFILE '/var/lib/mysql-files/job_type_info.csv'
INTO TABLE JOB_TYPE_INFO
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;

LOAD DATA INFILE '/var/lib/mysql-files/car_info.csv'
INTO TABLE CAR_INFO
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;

LOAD DATA INFILE '/var/lib/mysql-files/user_info.csv'
INTO TABLE USER_INFO
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;

LOAD DATA INFILE '/var/lib/mysql-files/car_review_info.csv'
INTO TABLE CAR_REVIEW_INFO
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;

LOAD DATA INFILE '/var/lib/mysql-files/comment_info.csv'
INTO TABLE COMMENT_INFO
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;

LOAD DATA INFILE '/var/lib/mysql-files/car_recommendation_info.csv'
INTO TABLE CAR_RECOMMENDATION_INFO
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;
